SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='harbor.nvspdren.navy.mil/tap/workloads/another-java-project-gary')
LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='gary')

k8s_custom_deploy(
    'another-java-project',
    apply_cmd="tanzu apps workload apply -f config/workload.yaml --debug --live-update" +
               " --local-path " + LOCAL_PATH +
               " --source-image " + SOURCE_IMAGE +
               " --namespace " + NAMESPACE +
               " --yes " +
               "--registry-ca-cert C:\\Gary\\Projects\\TKG\\samples\\harbor.nvspdren.navy.mil.crt " +
               " > NUL" +
               " && tanzu apps workload get another-java-project --namespace " + NAMESPACE + " -o yaml",
    delete_cmd="tanzu apps workload delete -f config/workload.yaml --namespace " + NAMESPACE + " --yes",
    deps=['pom.xml', './target/classes'],
    container_selector='workload',
    live_update=[
      sync('./target/classes', '/workspace/BOOT-INF/classes')
    ]
)

k8s_resource('another-java-project', port_forwards=["8080:8080"],
            extra_pod_selectors=[{'carto.run/workload-name': 'another-java-project', 'app.kubernetes.io/component': 'run'}])

allow_k8s_contexts('tap')