apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: another-java-project
    apps.tanzu.vmware.com/workload-type: web
  name: another-java-project
  namespace: boats
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "19"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/alexbarbato/application-accelerator-samples
    subPath: tanzu-java-web-app